services:
  nginx:
    image: nginx:1.25.3
    container_name: nginx_proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    command: /bin/bash -c "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    ports:
      - "8081:80"
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    ports:
      - "8082:80"
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 5s
      timeout: 2s
      retries: 3
